// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP59WIsQWf6dzur0M_-miqKrgZZMtoOxQ',
    appId: '1:721652556891:web:48f6f877097665ef5a8b7e',
    messagingSenderId: '721652556891',
    projectId: 'mon-car-a5a97',
    authDomain: 'mon-car-a5a97.firebaseapp.com',
    storageBucket: 'mon-car-a5a97.firebasestorage.app',
    measurementId: 'G-K29XV1EH48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG1IJKQZP91WmTTkrUuQV8py_dkRBhZFQ',
    appId: '1:721652556891:android:7fb9fc859e9196645a8b7e',
    messagingSenderId: '721652556891',
    projectId: 'mon-car-a5a97',
    storageBucket: 'mon-car-a5a97.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3GBnMoGrCUhynUGBMlB0wFP4nPyYIoUY',
    appId: '1:721652556891:ios:7e04a917652d0ee25a8b7e',
    messagingSenderId: '721652556891',
    projectId: 'mon-car-a5a97',
    storageBucket: 'mon-car-a5a97.firebasestorage.app',
    iosClientId:
        '721652556891-b4ratfosin12smv98mflmj7nduogeek0.apps.googleusercontent.com',
    iosBundleId: 'com.moncar.moncarClient',
  );
}
